/* GENERATED by data/generate.py — do not edit by hand.
   Every value is simulated. Aadhaar numbers begin 0000, a range no real
   Aadhaar can occupy. Loaded by portal.html via <script>, because file://
   cannot fetch local JSON. */
window.DB = {
  "aadhaar_record_sim": [
    {
      "aadhaar_sim": "000012345678",
      "name": "Sunita Deshpande",
      "dob": "1958-03-14",
      "mobile_sim": "+91 98765 43210",
      "email_sim": "sunita@example.com",
      "address_pincode": "411038"
    },
    {
      "aadhaar_sim": "000023456789",
      "name": "Rahul Verma",
      "dob": "2010-11-02",
      "mobile_sim": "+91 98765 43211",
      "email_sim": "rahul@example.com",
      "address_pincode": "560076"
    },
    {
      "aadhaar_sim": "000034567890",
      "name": "Priya Nair",
      "dob": "1999-06-21",
      "mobile_sim": "+91 98765 43212",
      "email_sim": "priya@example.com",
      "address_pincode": "682024"
    },
    {
      "aadhaar_sim": "000045678901",
      "name": "Imran Qureshi",
      "dob": "1987-01-09",
      "mobile_sim": "+91 98765 43213",
      "email_sim": "imran@example.com",
      "address_pincode": "226010"
    },
    {
      "aadhaar_sim": "000056789012",
      "name": "Meera Iyer",
      "dob": "1994-09-30",
      "mobile_sim": "+91 98765 43214",
      "email_sim": "meera@example.com",
      "address_pincode": "600042"
    },
    {
      "aadhaar_sim": "000067890123",
      "name": "Devendra Patil",
      "dob": "1976-04-17",
      "mobile_sim": "+91 98765 43215",
      "email_sim": "devendra@example.com",
      "address_pincode": "440015"
    }
  ],
  "citizen_account": [
    {
      "id": "acc_01",
      "aadhaar_sim": "000012345678",
      "created_at": "2026-08-01T09:00:00+05:30",
      "accessibility_prefs": {
        "large_text": true,
        "read_aloud": false,
        "language": "en"
      }
    },
    {
      "id": "acc_02",
      "aadhaar_sim": "000023456789",
      "created_at": "2026-08-01T09:00:00+05:30",
      "accessibility_prefs": {
        "large_text": false,
        "read_aloud": false,
        "language": "en"
      }
    },
    {
      "id": "acc_03",
      "aadhaar_sim": "000034567890",
      "created_at": "2026-08-01T09:00:00+05:30",
      "accessibility_prefs": {
        "large_text": false,
        "read_aloud": false,
        "language": "en"
      }
    },
    {
      "id": "acc_04",
      "aadhaar_sim": "000045678901",
      "created_at": "2026-08-01T09:00:00+05:30",
      "accessibility_prefs": {
        "large_text": false,
        "read_aloud": false,
        "language": "en"
      }
    },
    {
      "id": "acc_05",
      "aadhaar_sim": "000056789012",
      "created_at": "2026-08-01T09:00:00+05:30",
      "accessibility_prefs": {
        "large_text": false,
        "read_aloud": false,
        "language": "en"
      }
    },
    {
      "id": "acc_06",
      "aadhaar_sim": "000067890123",
      "created_at": "2026-08-01T09:00:00+05:30",
      "accessibility_prefs": {
        "large_text": false,
        "read_aloud": false,
        "language": "en"
      }
    }
  ],
  "cyber_office": [
    {
      "id": "off_01",
      "name": "Cyber Crime Police Station, Pune City",
      "address": "2nd Floor, Police Commissionerate, Camp",
      "pincode": "411001",
      "jurisdiction_pincodes": [
        "411001",
        "411038",
        "411045"
      ],
      "phone": "+91 80 4710 1001",
      "email": "cyber.pune@example.com"
    },
    {
      "id": "off_02",
      "name": "Cyber Crime Police Station, Bengaluru South",
      "address": "CID Annexe, Palace Road",
      "pincode": "560001",
      "jurisdiction_pincodes": [
        "560001",
        "560076",
        "560103"
      ],
      "phone": "+91 80 4710 1002",
      "email": "cyber.blr@example.com"
    },
    {
      "id": "off_03",
      "name": "Cyber Crime Police Station, Kochi City",
      "address": "Commissioner's Office, Marine Drive",
      "pincode": "682011",
      "jurisdiction_pincodes": [
        "682011",
        "682024"
      ],
      "phone": "+91 80 4710 1003",
      "email": "cyber.kochi@example.com"
    },
    {
      "id": "off_04",
      "name": "Cyber Crime Police Station, Lucknow",
      "address": "Gomti Nagar Extension",
      "pincode": "226010",
      "jurisdiction_pincodes": [
        "226010",
        "226016"
      ],
      "phone": "+91 80 4710 1004",
      "email": "cyber.lko@example.com"
    },
    {
      "id": "off_05",
      "name": "Cyber Crime Police Station, Chennai Central",
      "address": "Vepery High Road",
      "pincode": "600007",
      "jurisdiction_pincodes": [
        "600007",
        "600042"
      ],
      "phone": "+91 80 4710 1005",
      "email": "cyber.chn@example.com"
    },
    {
      "id": "off_06",
      "name": "Cyber Crime Police Station, Nagpur",
      "address": "Civil Lines",
      "pincode": "440001",
      "jurisdiction_pincodes": [
        "440001",
        "440015"
      ],
      "phone": "+91 80 4710 1006",
      "email": "cyber.ngp@example.com"
    }
  ],
  "officer": [
    {
      "id": "ofc_01",
      "office_id": "off_01",
      "name": "Insp. A. Kulkarni",
      "designation": "Inspector",
      "phone": "+91 80 4710 2010",
      "email": "a.kulkarni@example.com",
      "languages": [
        "Marathi",
        "Hindi",
        "English"
      ]
    },
    {
      "id": "ofc_02",
      "office_id": "off_02",
      "name": "SI R. Gowda",
      "designation": "Sub-Inspector",
      "phone": "+91 80 4710 2020",
      "email": "r.gowda@example.com",
      "languages": [
        "Kannada",
        "Hindi",
        "English"
      ]
    },
    {
      "id": "ofc_03",
      "office_id": "off_03",
      "name": "Insp. S. Menon",
      "designation": "Inspector",
      "phone": "+91 80 4710 2030",
      "email": "s.menon@example.com",
      "languages": [
        "Malayalam",
        "English"
      ]
    },
    {
      "id": "ofc_04",
      "office_id": "off_04",
      "name": "SI N. Yadav",
      "designation": "Sub-Inspector",
      "phone": "+91 80 4710 2040",
      "email": "n.yadav@example.com",
      "languages": [
        "Hindi",
        "English"
      ]
    },
    {
      "id": "ofc_05",
      "office_id": "off_05",
      "name": "Insp. K. Rajan",
      "designation": "Inspector",
      "phone": "+91 80 4710 2050",
      "email": "k.rajan@example.com",
      "languages": [
        "Tamil",
        "English"
      ]
    },
    {
      "id": "ofc_06",
      "office_id": "off_06",
      "name": "Insp. V. Thakre",
      "designation": "Inspector",
      "phone": "+91 80 4710 2060",
      "email": "v.thakre@example.com",
      "languages": [
        "Marathi",
        "Hindi"
      ]
    }
  ],
  "scenario": [
    {
      "id": "A1",
      "group": "A",
      "group_name": "Harm to identity and reputation",
      "title": "Cyber bullying, harassment or stalking",
      "urgency": "P1-LIVE",
      "first_question": "Is it still happening right now?",
      "modules": [
        "web_artifact",
        "online_identity",
        "communication_event"
      ],
      "money": "none"
    },
    {
      "id": "A2",
      "group": "A",
      "group_name": "Harm to identity and reputation",
      "title": "Someone made a fake account of me",
      "urgency": "P1-LIVE",
      "first_question": "Is the fake profile still up?",
      "modules": [
        "online_identity",
        "web_artifact"
      ],
      "money": "none"
    },
    {
      "id": "A3",
      "group": "A",
      "group_name": "Harm to identity and reputation",
      "title": "Fake news or a defamatory post about me",
      "urgency": "P1-LIVE",
      "first_question": "Where is it posted, and how many have seen it?",
      "modules": [
        "web_artifact",
        "online_identity"
      ],
      "money": "none"
    },
    {
      "id": "A4",
      "group": "A",
      "group_name": "Harm to identity and reputation",
      "title": "Morphed or obscene images of me",
      "urgency": "P0-THREAT",
      "first_question": "Is it public, or only threatened?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "web_artifact",
        "threat_record"
      ],
      "money": "optional"
    },
    {
      "id": "A5",
      "group": "A",
      "group_name": "Harm to identity and reputation",
      "title": "My account was taken over",
      "urgency": "P1-ACCESS",
      "first_question": "Can you still log in?",
      "modules": [
        "online_identity",
        "device_event"
      ],
      "money": "none"
    },
    {
      "id": "B1",
      "group": "B",
      "group_name": "Threats and coercion",
      "title": "Sextortion or blackmail",
      "urgency": "P0-THREAT",
      "first_question": "Is there a deadline they gave you?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "threat_record",
        "communication_event",
        "online_identity"
      ],
      "money": "optional"
    },
    {
      "id": "B2",
      "group": "B",
      "group_name": "Threats and coercion",
      "title": "Fake CBI or police call (digital arrest)",
      "urgency": "P0-THREAT",
      "first_question": "Are you on a call with them right now?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "communication_event",
        "threat_record"
      ],
      "money": "optional"
    },
    {
      "id": "B3",
      "group": "B",
      "group_name": "Threats and coercion",
      "title": "Intimidating messages or emails",
      "urgency": "P0-THREAT",
      "first_question": "Do they know where you live?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "communication_event"
      ],
      "money": "optional"
    },
    {
      "id": "C1",
      "group": "C",
      "group_name": "Money is gone",
      "title": "Fraud call, then I transferred money",
      "urgency": "P0-MONEY",
      "first_question": "When did the money leave?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "communication_event"
      ],
      "money": "required"
    },
    {
      "id": "C2",
      "group": "C",
      "group_name": "Money is gone",
      "title": "UPI or wallet fraud",
      "urgency": "P0-MONEY",
      "first_question": "When did the money leave?",
      "modules": [
        "complaint_money",
        "financial_transaction"
      ],
      "money": "required"
    },
    {
      "id": "C3",
      "group": "C",
      "group_name": "Money is gone",
      "title": "Card fraud or SIM swap",
      "urgency": "P0-MONEY",
      "first_question": "Is your SIM still working?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "device_event"
      ],
      "money": "required"
    },
    {
      "id": "C4",
      "group": "C",
      "group_name": "Money is gone",
      "title": "Net banking fraud",
      "urgency": "P0-MONEY",
      "first_question": "Do you still control the account?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "device_event"
      ],
      "money": "required"
    },
    {
      "id": "C5",
      "group": "C",
      "group_name": "Money is gone",
      "title": "Fake investment or trading app",
      "urgency": "P0-MONEY",
      "first_question": "How many payments did you make?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "web_artifact"
      ],
      "money": "required"
    },
    {
      "id": "C6",
      "group": "C",
      "group_name": "Money is gone",
      "title": "Loan app fraud and harassment",
      "urgency": "P0-THREAT",
      "first_question": "Are they contacting your contacts?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "communication_event",
        "threat_record"
      ],
      "money": "optional"
    },
    {
      "id": "C7",
      "group": "C",
      "group_name": "Money is gone",
      "title": "Job fraud",
      "urgency": "P2",
      "first_question": "Did you pay a registration fee?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "communication_event"
      ],
      "money": "required"
    },
    {
      "id": "C8",
      "group": "C",
      "group_name": "Money is gone",
      "title": "Matrimonial fraud",
      "urgency": "P2",
      "first_question": "How long did it go on?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "online_identity"
      ],
      "money": "required"
    },
    {
      "id": "C9",
      "group": "C",
      "group_name": "Money is gone",
      "title": "Crypto fraud",
      "urgency": "P0-MONEY",
      "first_question": "Do you have the wallet address?",
      "modules": [
        "complaint_money",
        "financial_transaction"
      ],
      "money": "required"
    },
    {
      "id": "D1",
      "group": "D",
      "group_name": "Deception vectors",
      "title": "Phishing link",
      "urgency": "P1-ACCESS",
      "first_question": "Did you enter anything on it?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "web_artifact",
        "communication_event"
      ],
      "money": "optional"
    },
    {
      "id": "D2",
      "group": "D",
      "group_name": "Deception vectors",
      "title": "Fake website or app",
      "urgency": "P1-LIVE",
      "first_question": "Is it still online?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "web_artifact"
      ],
      "money": "optional"
    },
    {
      "id": "D3",
      "group": "D",
      "group_name": "Deception vectors",
      "title": "QR code scam",
      "urgency": "P0-MONEY",
      "first_question": "Did you scan to receive, or to pay?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "web_artifact"
      ],
      "money": "optional"
    },
    {
      "id": "D4",
      "group": "D",
      "group_name": "Deception vectors",
      "title": "Fake customer care number",
      "urgency": "P0-MONEY",
      "first_question": "Where did you find the number?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "communication_event"
      ],
      "money": "optional"
    },
    {
      "id": "E1",
      "group": "E",
      "group_name": "Gaming",
      "title": "In-game items or currency stolen",
      "urgency": "P1-ACCESS",
      "first_question": "Can you still log in to the game?",
      "modules": [
        "online_identity"
      ],
      "money": "none"
    },
    {
      "id": "E2",
      "group": "E",
      "group_name": "Gaming",
      "title": "Gaming account taken over",
      "urgency": "P1-ACCESS",
      "first_question": "Is the email on the account still yours?",
      "modules": [
        "online_identity",
        "device_event"
      ],
      "money": "none"
    },
    {
      "id": "E3",
      "group": "E",
      "group_name": "Gaming",
      "title": "Paid for game currency, never received",
      "urgency": "P2",
      "first_question": "Who did you pay, and how?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "online_identity"
      ],
      "money": "optional"
    },
    {
      "id": "E4",
      "group": "E",
      "group_name": "Gaming",
      "title": "Grooming or bullying inside a game",
      "urgency": "P0-CHILD",
      "first_question": "How old is the person affected?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "communication_event",
        "online_identity",
        "web_artifact"
      ],
      "money": "optional"
    },
    {
      "id": "F1",
      "group": "F",
      "group_name": "Device and data",
      "title": "Hacking or unauthorised access",
      "urgency": "P1-ACCESS",
      "first_question": "Is the attacker still in?",
      "modules": [
        "device_event",
        "online_identity"
      ],
      "money": "none"
    },
    {
      "id": "F2",
      "group": "F",
      "group_name": "Device and data",
      "title": "Ransomware",
      "urgency": "P1-ACCESS",
      "first_question": "Have you disconnected the machine?",
      "modules": [
        "complaint_money",
        "financial_transaction",
        "device_event",
        "threat_record"
      ],
      "money": "optional"
    },
    {
      "id": "F3",
      "group": "F",
      "group_name": "Device and data",
      "title": "My data was leaked or breached",
      "urgency": "P2",
      "first_question": "What data, and where did you see it?",
      "modules": [
        "web_artifact",
        "online_identity"
      ],
      "money": "none"
    }
  ],
  "category": [
    {
      "id": "scam_call",
      "title": "Scam calls",
      "blurb": "Someone called pretending to be your bank, a company or an officer.",
      "icon": "phone",
      "scenario_ids": [
        "C1",
        "D4"
      ],
      "urgent": true
    },
    {
      "id": "money_gone",
      "title": "Money gone from my account",
      "blurb": "UPI, card, net banking or a wallet.",
      "icon": "card",
      "scenario_ids": [
        "C2",
        "C3",
        "C4"
      ],
      "urgent": true
    },
    {
      "id": "fake_invest",
      "title": "Fake investment or trading",
      "blurb": "An app or a group that promised returns.",
      "icon": "chart",
      "scenario_ids": [
        "C5",
        "C9"
      ],
      "urgent": true
    },
    {
      "id": "loan_app",
      "title": "Loan app trouble",
      "blurb": "Harassment, threats, or your contacts being called.",
      "icon": "alert",
      "scenario_ids": [
        "C6"
      ],
      "urgent": true
    },
    {
      "id": "digital_arrest",
      "title": "Fake police or CBI call",
      "blurb": "Being told you will be arrested unless you pay.",
      "icon": "badge",
      "scenario_ids": [
        "B2"
      ],
      "urgent": true
    },
    {
      "id": "blackmail",
      "title": "Blackmail or threats",
      "blurb": "Someone demanding money, or threatening to share something.",
      "icon": "shield",
      "scenario_ids": [
        "B1",
        "B3",
        "A4"
      ],
      "urgent": true
    },
    {
      "id": "job_marriage",
      "title": "Job or marriage fraud",
      "blurb": "A fee you paid, or someone you met online.",
      "icon": "briefcase",
      "scenario_ids": [
        "C7",
        "C8"
      ],
      "urgent": true
    },
    {
      "id": "fake_profile",
      "title": "Fake profile or photos of me",
      "blurb": "Someone pretending to be you, or posting about you.",
      "icon": "user",
      "scenario_ids": [
        "A2",
        "A3"
      ],
      "urgent": false
    },
    {
      "id": "bullying",
      "title": "Online bullying or stalking",
      "blurb": "Repeated messages, harassment or threats.",
      "icon": "message",
      "scenario_ids": [
        "A1"
      ],
      "urgent": false
    },
    {
      "id": "hacked",
      "title": "Account or device hacked",
      "blurb": "You cannot get in, or someone else is inside.",
      "icon": "lock",
      "scenario_ids": [
        "A5",
        "F1"
      ],
      "urgent": false
    },
    {
      "id": "suspicious",
      "title": "Suspicious link, QR or website",
      "blurb": "You spotted something and want it checked.",
      "icon": "link",
      "scenario_ids": [
        "D1",
        "D2",
        "D3"
      ],
      "urgent": false
    },
    {
      "id": "gaming",
      "title": "Gaming",
      "blurb": "In-game items, currency, or a game account.",
      "icon": "game",
      "scenario_ids": [
        "E1",
        "E2",
        "E3",
        "E4"
      ],
      "urgent": false
    },
    {
      "id": "ransomware",
      "title": "Files locked or data leaked",
      "blurb": "Ransomware, or your information appearing somewhere.",
      "icon": "file",
      "scenario_ids": [
        "F2",
        "F3"
      ],
      "urgent": false
    }
  ],
  "form_field": {
    "complaint_money": [
      {
        "name": "from_bank_wallet_sim",
        "label": "Which bank, wallet or app did the money leave?",
        "kind": "text",
        "help": "The one that sent the money, not the one that received it.",
        "options": null,
        "seven": true,
        "optional": false
      },
      {
        "name": "from_account_last4_sim",
        "label": "Last 4 digits of that account",
        "kind": "text",
        "help": "Only the last four. Never the full number.",
        "options": null,
        "seven": true,
        "optional": false
      },
      {
        "name": "card_last4_sim",
        "label": "Last 4 digits of the card",
        "kind": "text",
        "help": "Only if a card was used.",
        "options": null,
        "seven": true,
        "optional": true
      },
      {
        "name": "noticed_at",
        "label": "When did you notice?",
        "kind": "datetime",
        "help": "Different from when it happened, and both are useful.",
        "options": null,
        "seven": false,
        "optional": true
      }
    ],
    "financial_transaction": [
      {
        "name": "amount_inr",
        "label": "How much left your account?",
        "kind": "money",
        "help": "If there were several payments, add each one — the total is what matters.",
        "options": null,
        "seven": false,
        "optional": false
      },
      {
        "name": "rail",
        "label": "How was it paid?",
        "kind": "select",
        "help": "",
        "options": [
          "UPI",
          "Net banking",
          "IMPS or NEFT",
          "Card",
          "Wallet",
          "Crypto"
        ],
        "seven": false,
        "optional": false
      },
      {
        "name": "txn_id_utr_sim",
        "label": "Transaction ID or UTR",
        "kind": "text",
        "help": "Usually 12 digits. The one number a bank uses to find the money. Leave blank if you cannot find it.",
        "options": null,
        "seven": true,
        "optional": true
      },
      {
        "name": "txn_at",
        "label": "When did the money leave?",
        "kind": "datetime",
        "help": "",
        "options": null,
        "seven": true,
        "optional": false
      },
      {
        "name": "to_identifier_sim",
        "label": "Where did it go?",
        "kind": "text",
        "help": "A UPI ID, account number, merchant name or wallet address, if you have it.",
        "options": null,
        "seven": false,
        "optional": true
      },
      {
        "name": "to_identifier_kind",
        "label": "What kind of destination was that?",
        "kind": "select",
        "help": "",
        "options": [
          "UPI ID",
          "Bank account",
          "Merchant",
          "Wallet",
          "Crypto wallet",
          "Card"
        ],
        "seven": false,
        "optional": true
      }
    ],
    "communication_event": [
      {
        "name": "still_ongoing",
        "label": "Are they contacting you right now?",
        "kind": "bool",
        "help": "Answer this first. It changes what we show you next.",
        "options": null,
        "seven": false,
        "optional": false
      },
      {
        "name": "medium",
        "label": "How did they reach you?",
        "kind": "select",
        "help": "",
        "options": [
          "Phone call",
          "Video call",
          "SMS",
          "WhatsApp",
          "Email",
          "Social media",
          "In an app"
        ],
        "seven": false,
        "optional": false
      },
      {
        "name": "direction",
        "label": "Who contacted whom?",
        "kind": "select",
        "help": "If you called a number you found online, say so — that number is the lead.",
        "options": [
          "They contacted me",
          "I contacted them"
        ],
        "seven": false,
        "optional": false
      },
      {
        "name": "counterparty_number_sim",
        "label": "Their number or username",
        "kind": "text",
        "help": "",
        "options": null,
        "seven": false,
        "optional": true
      },
      {
        "name": "occurred_at",
        "label": "When?",
        "kind": "datetime",
        "help": "",
        "options": null,
        "seven": false,
        "optional": false
      },
      {
        "name": "duration_sec",
        "label": "Roughly how long did it last, in minutes?",
        "kind": "number",
        "help": "",
        "options": null,
        "seven": false,
        "optional": true
      },
      {
        "name": "content_text",
        "label": "What did they say?",
        "kind": "textarea",
        "help": "Paste the message if you still have it.",
        "options": null,
        "seven": false,
        "optional": true
      }
    ],
    "online_identity": [
      {
        "name": "role",
        "label": "What is this account?",
        "kind": "select",
        "help": "",
        "options": [
          "The suspect's account",
          "An account pretending to be me",
          "My own account, compromised"
        ],
        "seven": false,
        "optional": false
      },
      {
        "name": "platform",
        "label": "Which platform or game?",
        "kind": "text",
        "help": "",
        "options": null,
        "seven": false,
        "optional": false
      },
      {
        "name": "handle_sim",
        "label": "Username or handle",
        "kind": "text",
        "help": "",
        "options": null,
        "seven": false,
        "optional": true
      },
      {
        "name": "profile_url_sim",
        "label": "Link to the profile",
        "kind": "url",
        "help": "",
        "options": null,
        "seven": false,
        "optional": true
      },
      {
        "name": "is_active",
        "label": "Is the account still active?",
        "kind": "bool",
        "help": "",
        "options": null,
        "seven": false,
        "optional": false
      },
      {
        "name": "asset_description",
        "label": "What was taken?",
        "kind": "textarea",
        "help": "Items, currency, followers, anything of value.",
        "options": null,
        "seven": false,
        "optional": true
      },
      {
        "name": "asset_value_inr",
        "label": "Roughly what was it worth in rupees?",
        "kind": "money",
        "help": "Give a figure even if you are guessing. Without one, this gets treated as trivial.",
        "options": null,
        "seven": false,
        "optional": true
      }
    ],
    "web_artifact": [
      {
        "name": "kind",
        "label": "What is it?",
        "kind": "select",
        "help": "",
        "options": [
          "A post",
          "An image",
          "A video",
          "A comment",
          "An article",
          "A profile",
          "A link",
          "A QR code",
          "A website",
          "An app"
        ],
        "seven": false,
        "optional": false
      },
      {
        "name": "is_live",
        "label": "Is it still up?",
        "kind": "bool",
        "help": "",
        "options": null,
        "seven": false,
        "optional": false
      },
      {
        "name": "url_sim",
        "label": "Link to it",
        "kind": "url",
        "help": "",
        "options": null,
        "seven": false,
        "optional": true
      },
      {
        "name": "is_public",
        "label": "Can anyone see it, or only certain people?",
        "kind": "select",
        "help": "",
        "options": [
          "Anyone can see it",
          "Only certain people"
        ],
        "seven": false,
        "optional": false
      },
      {
        "name": "received_via",
        "label": "How did it reach you?",
        "kind": "text",
        "help": "SMS, WhatsApp, email, a search result, a group.",
        "options": null,
        "seven": false,
        "optional": true
      },
      {
        "name": "what_it_asked_for",
        "label": "What did it ask you to do?",
        "kind": "text",
        "help": "Log in, pay, scan, install, share a code.",
        "options": null,
        "seven": false,
        "optional": true
      },
      {
        "name": "credentials_entered",
        "label": "Did you enter anything on it?",
        "kind": "bool",
        "help": "A password, a PIN, an OTP, card details.",
        "options": null,
        "seven": false,
        "optional": false
      },
      {
        "name": "depicts_victim",
        "label": "Does it show or name the person affected?",
        "kind": "bool",
        "help": "",
        "options": null,
        "seven": false,
        "optional": false
      },
      {
        "name": "first_seen_at",
        "label": "When did you first see it?",
        "kind": "datetime",
        "help": "",
        "options": null,
        "seven": false,
        "optional": true
      }
    ],
    "threat_record": [
      {
        "name": "threat_type",
        "label": "What are they threatening to do?",
        "kind": "select",
        "help": "",
        "options": [
          "Publish or share content",
          "Have someone arrested",
          "Physical harm",
          "Contact family or employer",
          "Damage or leak data"
        ],
        "seven": false,
        "optional": false
      },
      {
        "name": "deadline_at",
        "label": "Did they give you a deadline?",
        "kind": "datetime",
        "help": "If there is one, this moves to the front of the queue.",
        "options": null,
        "seven": false,
        "optional": true
      },
      {
        "name": "demand_amount_inr",
        "label": "How much are they demanding?",
        "kind": "money",
        "help": "",
        "options": null,
        "seven": false,
        "optional": true
      },
      {
        "name": "contacted_known_contacts",
        "label": "Have they contacted people you know?",
        "kind": "bool",
        "help": "",
        "options": null,
        "seven": false,
        "optional": false
      }
    ],
    "attachment": [
      {
        "name": "files",
        "label": "Screenshots, photos, recordings or documents",
        "kind": "files",
        "help": "A screenshot of the message, a photo of the receipt, a recording of the call, a screen recording, a bank statement. Any type, any size — attach as many as you like.",
        "options": null,
        "seven": false,
        "optional": true
      },
      {
        "name": "what_it_shows",
        "label": "What do these show?",
        "kind": "text",
        "help": "One line is enough. It saves the officer opening every file to find out.",
        "options": null,
        "seven": false,
        "optional": true
      }
    ],
    "location": [
      {
        "name": "current_pincode",
        "label": "PIN code where you are staying now",
        "kind": "text",
        "help": "This decides which cyber crime unit receives your report. If you are away from your registered address — studying, working, travelling — put where you actually are.",
        "options": null,
        "seven": false,
        "optional": false
      }
    ],
    "device_event": [
      {
        "name": "device_kind",
        "label": "Which device?",
        "kind": "select",
        "help": "",
        "options": [
          "Phone",
          "Laptop",
          "Desktop",
          "Tablet",
          "Router or network",
          "Business system"
        ],
        "seven": false,
        "optional": false
      },
      {
        "name": "attacker_still_has_access",
        "label": "Do they still have access?",
        "kind": "bool",
        "help": "If you are not sure, say no and we will treat it as ongoing anyway.",
        "options": null,
        "seven": false,
        "optional": false
      }
    ]
  },
  "status_copy": {
    "SUBMITTED": {
      "title": "Report sent",
      "means": "Your report reached the cyber cell. The clock on the bank request starts now.",
      "do": "Nothing. Keep your reference number somewhere you can find it.",
      "sla_days": 0
    },
    "RECEIVED_BY_UNIT": {
      "title": "Received by the unit",
      "means": "A person has it in their queue. It is not sitting in a system waiting to be noticed.",
      "do": "Nothing yet.",
      "sla_days": 1
    },
    "ASSIGNED": {
      "title": "Assigned to an officer",
      "means": "A named officer is handling it.",
      "do": "You can call the desk number on your report and quote your reference.",
      "sla_days": 2
    },
    "NEEDS_INFO": {
      "title": "They need one more thing",
      "means": "The officer cannot go further without one specific thing. It is always named.",
      "do": "Add the item they asked for. This is the only thing holding the case up.",
      "sla_days": 1
    },
    "ACTION_TAKEN:LIEN_REQUESTED": {
      "title": "Hold requested from the bank",
      "means": "Police have asked your bank to hold the money. The bank decides, not the police and not us.",
      "do": "Nothing. Most banks reply within a day or two, and you get an SMS either way.",
      "sla_days": 3
    },
    "ACTION_TAKEN:TAKEDOWN_REQUESTED": {
      "title": "Takedown requested from the platform",
      "means": "Police have asked the platform to remove the content.",
      "do": "Do not contact the poster yourself. Save any new copies you find.",
      "sla_days": 7
    },
    "ACTION_TAKEN:NOTICE_ISSUED": {
      "title": "Notice issued",
      "means": "A formal notice has gone to the person or company involved.",
      "do": "Nothing.",
      "sla_days": 15
    },
    "ACTION_TAKEN:SUSPECT_TRACED": {
      "title": "Account traced",
      "means": "The account or person that received your money has been identified.",
      "do": "Nothing. Your officer will tell you if a statement is needed.",
      "sla_days": 10
    },
    "FIR_REGISTERED": {
      "title": "FIR registered",
      "means": "A formal police case exists. An FIR is what lets police compel banks and platforms.",
      "do": "Keep the FIR number with your reference number.",
      "sla_days": 30
    },
    "CLOSED": {
      "title": "Closed",
      "means": "The case is finished. The outcome is stated plainly, good or bad.",
      "do": "If you disagree, the escalation ladder on your report still works.",
      "sla_days": 0
    },
    "WITHDRAWN": {
      "title": "Withdrawn",
      "means": "You asked for this report to be withdrawn.",
      "do": "Nothing. You can file again at any time.",
      "sla_days": 0
    }
  },
  "complaint": [
    {
      "id": "cmp_01",
      "reference_no": "CCR-SIM-2026-004182",
      "account_id": "acc_01",
      "reporter_relationship": "self",
      "victim_age_band": "senior",
      "victim_display_name": null,
      "narrative_raw": "Got a call from someone saying he was from my bank and my account would be blocked today. He knew my name. He asked for the OTP and I gave it. Rs 80,000 went out on UPI around 7:40 pm.",
      "scenario_ids": [
        "C1",
        "C2"
      ],
      "submitted_at": "2026-08-25T19:52:00+05:30",
      "is_protected_identity": false
    },
    {
      "id": "cmp_02",
      "reference_no": "CCR-SIM-2026-003911",
      "account_id": "acc_04",
      "reporter_relationship": "self",
      "victim_age_band": "adult",
      "victim_display_name": null,
      "narrative_raw": "I joined a WhatsApp group about share trading. The app showed my profit going up. I paid four times. When I tried to withdraw they asked for a tax payment and then removed me from the group.",
      "scenario_ids": [
        "C5"
      ],
      "submitted_at": "2026-08-18T14:10:00+05:30",
      "is_protected_identity": false
    },
    {
      "id": "cmp_03",
      "reference_no": "CCR-SIM-2026-004055",
      "account_id": "acc_06",
      "reporter_relationship": "child_relative",
      "victim_age_band": "senior",
      "victim_display_name": "D. Patil",
      "narrative_raw": "A video call came from people in police uniform saying a parcel in my father's name had drugs and he would be arrested. They kept him on the call for two hours. He transferred Rs 2,50,000.",
      "scenario_ids": [
        "B2",
        "C1"
      ],
      "submitted_at": "2026-08-22T12:05:00+05:30",
      "is_protected_identity": false
    },
    {
      "id": "cmp_04",
      "reference_no": "CCR-SIM-2026-004120",
      "account_id": "acc_05",
      "reporter_relationship": "self",
      "victim_age_band": "adult",
      "victim_display_name": null,
      "narrative_raw": "My phone stopped getting signal in the evening. By morning Rs 62,000 had gone from my card. The bank said an OTP was used. I never received it.",
      "scenario_ids": [
        "C3"
      ],
      "submitted_at": "2026-08-24T08:30:00+05:30",
      "is_protected_identity": false
    },
    {
      "id": "cmp_05",
      "reference_no": "CCR-SIM-2026-004160",
      "account_id": "acc_03",
      "reporter_relationship": "self",
      "victim_age_band": "adult",
      "victim_display_name": null,
      "narrative_raw": "Someone wanted to buy my sofa on a marketplace. He sent a QR code and said scanning it would send me the money. I scanned it and entered my PIN and Rs 14,500 left my account instead.",
      "scenario_ids": [
        "D3"
      ],
      "submitted_at": "2026-08-24T16:20:00+05:30",
      "is_protected_identity": false
    },
    {
      "id": "cmp_06",
      "reference_no": "CCR-SIM-2026-004044",
      "account_id": "acc_02",
      "reporter_relationship": "self",
      "victim_age_band": "minor",
      "victim_display_name": null,
      "narrative_raw": "A group from my class made a page about me and keep posting edited photos. I do not want my parents to find out.",
      "scenario_ids": [
        "A1",
        "A2"
      ],
      "submitted_at": "2026-08-19T21:40:00+05:30",
      "is_protected_identity": true
    },
    {
      "id": "cmp_07",
      "reference_no": "CCR-SIM-2026-004071",
      "account_id": "acc_03",
      "reporter_relationship": "self",
      "victim_age_band": "adult",
      "victim_display_name": null,
      "narrative_raw": "Someone morphed my photo and says they will post it unless I pay.",
      "scenario_ids": [
        "A4",
        "B1"
      ],
      "submitted_at": "2026-08-21T23:05:00+05:30",
      "is_protected_identity": true
    },
    {
      "id": "cmp_08",
      "reference_no": "CCR-SIM-2026-004098",
      "account_id": "acc_02",
      "reporter_relationship": "parent_guardian",
      "victim_age_band": "minor",
      "victim_display_name": "R. Verma",
      "narrative_raw": "Someone got into my son's game account and moved his skins and coins to another account. He paid real money for those over two years.",
      "scenario_ids": [
        "E1",
        "E2"
      ],
      "submitted_at": "2026-08-23T18:15:00+05:30",
      "is_protected_identity": false
    },
    {
      "id": "cmp_09",
      "reference_no": "CCR-SIM-2026-004135",
      "account_id": "acc_04",
      "reporter_relationship": "self",
      "victim_age_band": "adult",
      "victim_display_name": null,
      "narrative_raw": "Our office desktop and the backup drive are both locked. A note on screen asks for payment in crypto by Friday. The business has stopped.",
      "scenario_ids": [
        "F2"
      ],
      "submitted_at": "2026-08-24T10:40:00+05:30",
      "is_protected_identity": false
    }
  ],
  "routing": [
    {
      "complaint_id": "cmp_01",
      "id": "rt_01",
      "office_id": "off_01",
      "officer_id": "ofc_01",
      "routed_at": "2026-08-25T19:52:00+05:30",
      "routed_by_rule": "victim_pincode",
      "is_cross_state": false
    },
    {
      "complaint_id": "cmp_02",
      "id": "rt_02",
      "office_id": "off_04",
      "officer_id": "ofc_04",
      "routed_at": "2026-08-18T14:10:00+05:30",
      "routed_by_rule": "victim_pincode",
      "is_cross_state": false
    },
    {
      "complaint_id": "cmp_03",
      "id": "rt_03",
      "office_id": "off_06",
      "officer_id": "ofc_06",
      "routed_at": "2026-08-22T12:05:00+05:30",
      "routed_by_rule": "victim_pincode",
      "is_cross_state": false
    },
    {
      "complaint_id": "cmp_04",
      "id": "rt_04",
      "office_id": "off_05",
      "officer_id": "ofc_05",
      "routed_at": "2026-08-24T08:30:00+05:30",
      "routed_by_rule": "victim_pincode",
      "is_cross_state": false
    },
    {
      "complaint_id": "cmp_05",
      "id": "rt_05",
      "office_id": "off_03",
      "officer_id": "ofc_03",
      "routed_at": "2026-08-24T16:20:00+05:30",
      "routed_by_rule": "victim_pincode",
      "is_cross_state": false
    },
    {
      "complaint_id": "cmp_06",
      "id": "rt_06",
      "office_id": "off_02",
      "officer_id": "ofc_02",
      "routed_at": "2026-08-19T21:40:00+05:30",
      "routed_by_rule": "victim_pincode",
      "is_cross_state": false
    },
    {
      "complaint_id": "cmp_07",
      "id": "rt_07",
      "office_id": "off_03",
      "officer_id": "ofc_03",
      "routed_at": "2026-08-21T23:05:00+05:30",
      "routed_by_rule": "victim_pincode",
      "is_cross_state": false
    },
    {
      "complaint_id": "cmp_08",
      "id": "rt_08",
      "office_id": "off_02",
      "officer_id": "ofc_02",
      "routed_at": "2026-08-23T18:15:00+05:30",
      "routed_by_rule": "victim_pincode",
      "is_cross_state": false
    },
    {
      "complaint_id": "cmp_09",
      "id": "rt_09",
      "office_id": "off_04",
      "officer_id": "ofc_04",
      "routed_at": "2026-08-24T10:40:00+05:30",
      "routed_by_rule": "victim_pincode",
      "is_cross_state": false
    }
  ],
  "complaint_money": [
    {
      "complaint_id": "cmp_01",
      "from_bank_wallet_sim": "State Bank of India",
      "from_account_last4_sim": "4471",
      "card_last4_sim": null,
      "noticed_at": "2026-08-25T19:48:00+05:30"
    },
    {
      "complaint_id": "cmp_02",
      "from_bank_wallet_sim": "State Bank of India",
      "from_account_last4_sim": "8820",
      "card_last4_sim": null,
      "noticed_at": "2026-08-18T13:30:00+05:30"
    },
    {
      "complaint_id": "cmp_03",
      "from_bank_wallet_sim": "State Bank of India",
      "from_account_last4_sim": "6612",
      "card_last4_sim": null,
      "noticed_at": "2026-08-22T11:55:00+05:30"
    },
    {
      "complaint_id": "cmp_04",
      "from_bank_wallet_sim": "State Bank of India",
      "from_account_last4_sim": "4471",
      "card_last4_sim": "4471",
      "noticed_at": "2026-08-24T07:50:00+05:30"
    },
    {
      "complaint_id": "cmp_05",
      "from_bank_wallet_sim": "Paytm Wallet",
      "from_account_last4_sim": "9013",
      "card_last4_sim": null,
      "noticed_at": "2026-08-24T16:07:00+05:30"
    }
  ],
  "financial_transaction": [
    {
      "complaint_id": "cmp_01",
      "id": "txn_01",
      "amount_inr": 80000,
      "rail": "upi",
      "txn_id_utr_sim": "441922078853",
      "txn_at": "2026-08-25T19:42:00+05:30",
      "to_identifier_sim": "rk.traders@ybl",
      "to_identifier_kind": "upi"
    },
    {
      "complaint_id": "cmp_02",
      "id": "txn_02",
      "amount_inr": 5000,
      "rail": "upi",
      "txn_id_utr_sim": "338104772910",
      "txn_at": "2026-07-02T11:15:00+05:30",
      "to_identifier_sim": "gm.ventures@okaxis",
      "to_identifier_kind": "upi"
    },
    {
      "complaint_id": "cmp_02",
      "id": "txn_03",
      "amount_inr": 25000,
      "rail": "imps",
      "txn_id_utr_sim": "338119024466",
      "txn_at": "2026-07-14T16:40:00+05:30",
      "to_identifier_sim": "A/c ending 3391",
      "to_identifier_kind": "account"
    },
    {
      "complaint_id": "cmp_02",
      "id": "txn_04",
      "amount_inr": 120000,
      "rail": "netbanking",
      "txn_id_utr_sim": "441806335128",
      "txn_at": "2026-08-01T10:05:00+05:30",
      "to_identifier_sim": "A/c ending 3391",
      "to_identifier_kind": "account"
    },
    {
      "complaint_id": "cmp_02",
      "id": "txn_05",
      "amount_inr": 200000,
      "rail": "netbanking",
      "txn_id_utr_sim": "441822901774",
      "txn_at": "2026-08-18T09:22:00+05:30",
      "to_identifier_sim": "A/c ending 3391",
      "to_identifier_kind": "account"
    },
    {
      "complaint_id": "cmp_03",
      "id": "txn_06",
      "amount_inr": 250000,
      "rail": "netbanking",
      "txn_id_utr_sim": "552211480637",
      "txn_at": "2026-08-22T11:40:00+05:30",
      "to_identifier_sim": "A/c ending 7745",
      "to_identifier_kind": "account"
    },
    {
      "complaint_id": "cmp_04",
      "id": "txn_07",
      "amount_inr": 62000,
      "rail": "card",
      "txn_id_utr_sim": "771043928155",
      "txn_at": "2026-08-24T02:11:00+05:30",
      "to_identifier_sim": "Online merchant, Singapore",
      "to_identifier_kind": "merchant"
    },
    {
      "complaint_id": "cmp_05",
      "id": "txn_08",
      "amount_inr": 14500,
      "rail": "upi",
      "txn_id_utr_sim": "441924460388",
      "txn_at": "2026-08-24T16:05:00+05:30",
      "to_identifier_sim": "rk.traders@ybl",
      "to_identifier_kind": "upi"
    }
  ],
  "communication_event": [
    {
      "complaint_id": "cmp_01",
      "id": "ce_01",
      "medium": "call",
      "direction": "inbound",
      "counterparty_number_sim": "+91 79045 11238",
      "counterparty_handle_sim": null,
      "occurred_at": "2026-08-25T19:31:00+05:30",
      "duration_sec": 640,
      "content_text": "Caller claimed to be from the bank's fraud desk.",
      "still_ongoing": false,
      "evidence_attachment_id": "att_01"
    },
    {
      "complaint_id": "cmp_03",
      "id": "ce_02",
      "medium": "video_call",
      "direction": "inbound",
      "counterparty_number_sim": "+91 63820 77451",
      "counterparty_handle_sim": null,
      "occurred_at": "2026-08-22T09:38:00+05:30",
      "duration_sec": 7920,
      "content_text": "Callers in uniform, fake CBI backdrop. Told him hanging up was an admission of guilt.",
      "still_ongoing": false,
      "evidence_attachment_id": null
    }
  ],
  "online_identity": [
    {
      "complaint_id": "cmp_06",
      "id": "oi_01",
      "role": "impersonating_victim",
      "platform": "SocialApp",
      "handle_sim": "notpriya_real",
      "profile_url_sim": "https://socialapp.example/notpriya_real",
      "display_name_sim": "Priya N.",
      "first_seen_at": "2026-08-19T00:00:00+05:30",
      "is_active": true,
      "asset_description": null,
      "asset_value_inr": null
    },
    {
      "complaint_id": "cmp_08",
      "id": "oi_02",
      "role": "victim_compromised",
      "platform": "Skyforge Online",
      "handle_sim": "notpriya_real",
      "profile_url_sim": null,
      "display_name_sim": null,
      "first_seen_at": "2026-08-23T17:00:00+05:30",
      "is_active": false,
      "asset_description": "2 rare skins and roughly 12,000 in-game coins",
      "asset_value_inr": 31000
    }
  ],
  "web_artifact": [
    {
      "complaint_id": "cmp_02",
      "id": "wa_01",
      "url_sim": "https://quantx-pro.trade",
      "kind": "app",
      "is_public": true,
      "is_live": true,
      "first_seen_at": "2026-06-28T00:00:00+05:30",
      "received_via": "WhatsApp group invite",
      "what_it_asked_for": "deposits and a withdrawal tax",
      "credentials_entered": false,
      "depicts_victim": false,
      "evidence_attachment_id": "att_02"
    },
    {
      "complaint_id": "cmp_05",
      "id": "wa_02",
      "url_sim": "upi://pay?pa=rk.traders@ybl&am=14500",
      "kind": "qr",
      "is_public": false,
      "is_live": false,
      "first_seen_at": "2026-08-24T16:02:00+05:30",
      "received_via": "WhatsApp, from the buyer",
      "what_it_asked_for": "payment",
      "credentials_entered": true,
      "depicts_victim": false,
      "evidence_attachment_id": null
    },
    {
      "complaint_id": "cmp_06",
      "id": "wa_03",
      "url_sim": "https://socialapp.example/p/9f31c",
      "kind": "profile",
      "is_public": true,
      "is_live": true,
      "first_seen_at": "2026-08-19T00:00:00+05:30",
      "received_via": null,
      "what_it_asked_for": null,
      "credentials_entered": false,
      "depicts_victim": true,
      "evidence_attachment_id": "att_03"
    },
    {
      "complaint_id": "cmp_07",
      "id": "wa_04",
      "url_sim": null,
      "kind": "image",
      "is_public": false,
      "is_live": false,
      "first_seen_at": "2026-08-21T22:40:00+05:30",
      "received_via": "Direct message",
      "what_it_asked_for": null,
      "credentials_entered": false,
      "depicts_victim": true,
      "evidence_attachment_id": null
    }
  ],
  "threat_record": [
    {
      "complaint_id": "cmp_03",
      "id": "tr_01",
      "threat_type": "arrest",
      "demand_amount_inr": 250000,
      "deadline_at": "2026-08-22T13:00:00+05:30",
      "contacted_known_contacts": false
    },
    {
      "complaint_id": "cmp_07",
      "id": "tr_02",
      "threat_type": "expose_content",
      "demand_amount_inr": 15000,
      "deadline_at": "2026-08-26T20:00:00+05:30",
      "contacted_known_contacts": true
    },
    {
      "complaint_id": "cmp_09",
      "id": "tr_03",
      "threat_type": "expose_content",
      "demand_amount_inr": 400000,
      "deadline_at": "2026-08-28T00:00:00+05:30",
      "contacted_known_contacts": false
    }
  ],
  "device_event": [
    {
      "complaint_id": "cmp_04",
      "id": "de_01",
      "device_kind": "phone",
      "attacker_still_has_access": true
    },
    {
      "complaint_id": "cmp_09",
      "id": "de_02",
      "device_kind": "desktop",
      "attacker_still_has_access": null
    }
  ],
  "attachment": [
    {
      "complaint_id": "cmp_01",
      "id": "att_01",
      "filename": "bank-sms.png",
      "mime": "image/png",
      "capture_method": "screenshot",
      "sha256": "9f2c41ab7e05d3ca8814bb60f7392ad1c04e6b95",
      "scan_status": "clean",
      "what_it_shows": "The debit SMS from the bank",
      "uploaded_at": "2026-08-25T19:50:00+05:30"
    },
    {
      "complaint_id": "cmp_02",
      "id": "att_02",
      "filename": "app-screen-recording.mp4",
      "mime": "video/mp4",
      "capture_method": "screen_recording",
      "sha256": "9f2c41ab7e05d3ca8814bb60f7392ad1c04e6b95",
      "scan_status": "clean",
      "what_it_shows": "The fake profit dashboard, and the withdrawal being refused",
      "uploaded_at": "2026-08-18T14:08:00+05:30"
    },
    {
      "complaint_id": "cmp_06",
      "id": "att_03",
      "filename": "screenshots.pdf",
      "mime": "application/pdf",
      "capture_method": "file_picker",
      "sha256": "9f2c41ab7e05d3ca8814bb60f7392ad1c04e6b95",
      "scan_status": "clean",
      "what_it_shows": "Six posts from the page",
      "uploaded_at": "2026-08-19T21:38:00+05:30"
    },
    {
      "complaint_id": "cmp_09",
      "id": "att_04",
      "filename": "ransom-note.exe",
      "mime": "application/x-msdownload",
      "capture_method": "file_picker",
      "sha256": "9f2c41ab7e05d3ca8814bb60f7392ad1c04e6b95",
      "scan_status": "quarantined",
      "what_it_shows": "The dropper itself. Preserved for the forensic lab, never deleted.",
      "uploaded_at": "2026-08-24T10:38:00+05:30"
    }
  ],
  "complaint_note": [
    {
      "complaint_id": "cmp_01",
      "id": "nt_01",
      "body": "Victim called 1930 before filing. Reference quoted.",
      "author": "citizen",
      "created_at": "2026-08-25T19:55:00+05:30"
    },
    {
      "complaint_id": "cmp_02",
      "id": "nt_02",
      "body": "Officer asked for the UTR of the first payment.",
      "author": "officer",
      "created_at": "2026-08-20T10:15:00+05:30"
    },
    {
      "complaint_id": "cmp_03",
      "id": "nt_03",
      "body": "Reported by the victim's daughter. Victim is 72 and still shaken.",
      "author": "citizen",
      "created_at": "2026-08-22T12:07:00+05:30"
    },
    {
      "complaint_id": "cmp_04",
      "id": "nt_04",
      "body": "All contact by email. SMS channel unusable — this is the scenario that breaks it.",
      "author": "system",
      "created_at": "2026-08-24T08:30:00+05:30"
    },
    {
      "complaint_id": "cmp_06",
      "id": "nt_05",
      "body": "Child-protection routing applied. No guardian notification sent.",
      "author": "system",
      "created_at": "2026-08-19T21:40:00+05:30"
    },
    {
      "complaint_id": "cmp_07",
      "id": "nt_06",
      "body": "Identity masked in all case views. Reveal requires a logged action.",
      "author": "system",
      "created_at": "2026-08-21T23:05:00+05:30"
    },
    {
      "complaint_id": "cmp_09",
      "id": "nt_07",
      "body": "Containment advice shown before any question was asked.",
      "author": "system",
      "created_at": "2026-08-24T10:40:00+05:30"
    }
  ],
  "status_event": [
    {
      "complaint_id": "cmp_01",
      "id": "se_01a",
      "status": "SUBMITTED",
      "action_subtype": null,
      "occurred_at": "2026-08-25T19:52:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_01",
      "id": "se_01b",
      "status": "RECEIVED_BY_UNIT",
      "action_subtype": null,
      "occurred_at": "2026-08-25T19:53:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_01",
      "id": "se_01c",
      "status": "ASSIGNED",
      "action_subtype": null,
      "occurred_at": "2026-08-25T20:01:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_01",
      "id": "se_01d",
      "status": "ACTION_TAKEN",
      "action_subtype": "LIEN_REQUESTED",
      "occurred_at": "2026-08-25T20:06:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_02",
      "id": "se_02a",
      "status": "SUBMITTED",
      "action_subtype": null,
      "occurred_at": "2026-08-18T14:10:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_02",
      "id": "se_02b",
      "status": "RECEIVED_BY_UNIT",
      "action_subtype": null,
      "occurred_at": "2026-08-18T14:12:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_02",
      "id": "se_02c",
      "status": "ASSIGNED",
      "action_subtype": null,
      "occurred_at": "2026-08-18T15:30:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_02",
      "id": "se_02d",
      "status": "ACTION_TAKEN",
      "action_subtype": "LIEN_REQUESTED",
      "occurred_at": "2026-08-18T17:02:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_02",
      "id": "se_02e",
      "status": "NEEDS_INFO",
      "action_subtype": null,
      "occurred_at": "2026-08-20T10:15:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_03",
      "id": "se_03a",
      "status": "SUBMITTED",
      "action_subtype": null,
      "occurred_at": "2026-08-22T12:05:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_03",
      "id": "se_03b",
      "status": "RECEIVED_BY_UNIT",
      "action_subtype": null,
      "occurred_at": "2026-08-22T12:06:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_03",
      "id": "se_03c",
      "status": "ASSIGNED",
      "action_subtype": null,
      "occurred_at": "2026-08-22T12:20:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_03",
      "id": "se_03d",
      "status": "ACTION_TAKEN",
      "action_subtype": "LIEN_REQUESTED",
      "occurred_at": "2026-08-22T12:44:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_03",
      "id": "se_03e",
      "status": "ACTION_TAKEN",
      "action_subtype": "SUSPECT_TRACED",
      "occurred_at": "2026-08-24T16:00:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_03",
      "id": "se_03f",
      "status": "FIR_REGISTERED",
      "action_subtype": null,
      "occurred_at": "2026-08-25T11:00:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_04",
      "id": "se_04a",
      "status": "SUBMITTED",
      "action_subtype": null,
      "occurred_at": "2026-08-24T08:30:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_04",
      "id": "se_04b",
      "status": "RECEIVED_BY_UNIT",
      "action_subtype": null,
      "occurred_at": "2026-08-24T08:31:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_04",
      "id": "se_04c",
      "status": "ASSIGNED",
      "action_subtype": null,
      "occurred_at": "2026-08-24T09:15:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_04",
      "id": "se_04d",
      "status": "ACTION_TAKEN",
      "action_subtype": "LIEN_REQUESTED",
      "occurred_at": "2026-08-24T09:40:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_05",
      "id": "se_05a",
      "status": "SUBMITTED",
      "action_subtype": null,
      "occurred_at": "2026-08-24T16:20:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_05",
      "id": "se_05b",
      "status": "RECEIVED_BY_UNIT",
      "action_subtype": null,
      "occurred_at": "2026-08-24T16:21:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_06",
      "id": "se_06a",
      "status": "SUBMITTED",
      "action_subtype": null,
      "occurred_at": "2026-08-19T21:40:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_06",
      "id": "se_06b",
      "status": "RECEIVED_BY_UNIT",
      "action_subtype": null,
      "occurred_at": "2026-08-19T21:42:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_06",
      "id": "se_06c",
      "status": "ASSIGNED",
      "action_subtype": null,
      "occurred_at": "2026-08-20T10:00:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_06",
      "id": "se_06d",
      "status": "ACTION_TAKEN",
      "action_subtype": "TAKEDOWN_REQUESTED",
      "occurred_at": "2026-08-20T12:30:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_07",
      "id": "se_07a",
      "status": "SUBMITTED",
      "action_subtype": null,
      "occurred_at": "2026-08-21T23:05:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_07",
      "id": "se_07b",
      "status": "RECEIVED_BY_UNIT",
      "action_subtype": null,
      "occurred_at": "2026-08-21T23:06:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_07",
      "id": "se_07c",
      "status": "ASSIGNED",
      "action_subtype": null,
      "occurred_at": "2026-08-22T09:00:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_08",
      "id": "se_08a",
      "status": "SUBMITTED",
      "action_subtype": null,
      "occurred_at": "2026-08-23T18:15:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_08",
      "id": "se_08b",
      "status": "RECEIVED_BY_UNIT",
      "action_subtype": null,
      "occurred_at": "2026-08-23T18:20:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_08",
      "id": "se_08c",
      "status": "ASSIGNED",
      "action_subtype": null,
      "occurred_at": "2026-08-24T11:00:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_09",
      "id": "se_09a",
      "status": "SUBMITTED",
      "action_subtype": null,
      "occurred_at": "2026-08-24T10:40:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_09",
      "id": "se_09b",
      "status": "RECEIVED_BY_UNIT",
      "action_subtype": null,
      "occurred_at": "2026-08-24T10:41:00+05:30",
      "actor": "system"
    },
    {
      "complaint_id": "cmp_09",
      "id": "se_09c",
      "status": "ASSIGNED",
      "action_subtype": null,
      "occurred_at": "2026-08-24T12:00:00+05:30",
      "actor": "officer"
    },
    {
      "complaint_id": "cmp_09",
      "id": "se_09d",
      "status": "NEEDS_INFO",
      "action_subtype": null,
      "occurred_at": "2026-08-25T09:30:00+05:30",
      "actor": "officer"
    }
  ],
  "identity_reveal_log": [
    {
      "id": "irl_01",
      "complaint_id": "cmp_07",
      "revealed_by": "ofc_03",
      "revealed_at": "2026-08-22T09:12:00+05:30",
      "reason": "Needed to contact the victim to confirm the deadline in the threat."
    }
  ],
  "counterparty_cluster": [
    {
      "id": "cc_01",
      "identifier_sim": "rk.traders@ybl",
      "identifier_kind": "upi",
      "complaint_ids": [
        "cmp_01",
        "cmp_05"
      ],
      "total_amount_inr": 3140000,
      "victim_count": 42,
      "first_seen_at": "2026-08-04T00:00:00+05:30",
      "last_seen_at": "2026-08-25T19:42:00+05:30"
    },
    {
      "id": "cc_02",
      "identifier_sim": "gm.ventures@okaxis",
      "identifier_kind": "upi",
      "complaint_ids": [
        "cmp_02"
      ],
      "total_amount_inr": 890000,
      "victim_count": 17,
      "first_seen_at": "2026-08-11T00:00:00+05:30",
      "last_seen_at": "2026-08-18T09:22:00+05:30"
    },
    {
      "id": "cc_03",
      "identifier_sim": "+91 79045 11238",
      "identifier_kind": "phone",
      "complaint_ids": [
        "cmp_01"
      ],
      "total_amount_inr": 0,
      "victim_count": 96,
      "first_seen_at": "2026-08-02T00:00:00+05:30",
      "last_seen_at": "2026-08-25T19:31:00+05:30"
    },
    {
      "id": "cc_04",
      "identifier_sim": "https://quantx-pro.trade",
      "identifier_kind": "url",
      "complaint_ids": [
        "cmp_02"
      ],
      "total_amount_inr": 1210000,
      "victim_count": 23,
      "first_seen_at": "2026-06-28T00:00:00+05:30",
      "last_seen_at": "2026-08-18T09:22:00+05:30"
    },
    {
      "id": "cc_05",
      "identifier_sim": "0x7a3f…c19b (Ethereum)",
      "identifier_kind": "crypto_wallet",
      "complaint_ids": [],
      "total_amount_inr": 760000,
      "victim_count": 8,
      "first_seen_at": "2026-07-19T00:00:00+05:30",
      "last_seen_at": "2026-08-24T00:00:00+05:30"
    }
  ]
};
