import Link from "next/link";
import type { Metadata } from "next";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";

export const metadata: Metadata = {
  title: "What's real vs mocked — Cybercrime Report & Track",
  description:
    "An honest, specific account of what this prototype actually does, what is simulated, and what we deliberately did not build.",
};

function StatusRow({
  label,
  status,
  children,
}: {
  label: string;
  status: "Real" | "Mocked" | "Simulated" | "Not built";
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col gap-1 border-b border-border py-4 last:border-0 last:pb-0">
      <div className="flex flex-wrap items-center gap-2">
        <h3 className="font-medium text-foreground">{label}</h3>
        <Badge variant={status === "Real" ? "secondary" : "outline"}>{status}</Badge>
      </div>
      <p className="text-sm text-muted-foreground">{children}</p>
    </div>
  );
}

export default function WhatsRealPage() {
  return (
    <div className="mx-auto flex w-full max-w-2xl flex-col gap-10 px-4 py-12">
      <div className="flex flex-col gap-3">
        <h1 className="text-3xl font-semibold tracking-tight text-foreground">
          What&apos;s real, and what&apos;s mocked
        </h1>
        <p className="text-lg text-muted-foreground">
          This is a hackathon prototype, not an official government service. It does not have,
          does not claim, and cannot claim government-grade security. It demonstrates the{" "}
          <strong className="text-foreground">UX and architecture shape</strong> of what a
          production system would require — with mock and synthetic data only. It performs no
          real authentication, sends no real SMS, holds no real citizen data, and connects to no
          government system.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>The single most important fact on this page</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-foreground">
            <strong>
              Complaint IDs generated by this prototype are not real NCRP complaint numbers.
            </strong>{" "}
            They are not registered with cybercrime.gov.in, the National Cyber Crime Reporting
            Portal, CFCFRMS, or any police system. If you have actually been a victim of
            cybercrime, please use the real portal at{" "}
            <a
              href="https://cybercrime.gov.in"
              className="underline underline-offset-2 hover:text-foreground"
            >
              cybercrime.gov.in
            </a>{" "}
            or call <strong>1930</strong>.
          </p>
        </CardContent>
      </Card>

      <div className="flex flex-col gap-2">
        <h2 className="text-xl font-semibold tracking-tight text-foreground">
          Feature by feature
        </h2>
        <p className="text-sm text-muted-foreground">
          Every control in this product falls into one of four states. Nothing is left ambiguous.
        </p>
      </div>

      <Card>
        <CardContent className="flex flex-col divide-y-0">
          <StatusRow label="OTP / mobile verification" status="Mocked">
            No real SMS gateway exists. A fixed on-screen demo code is shown when you request an
            OTP, and a published fallback code works even if you never see the on-screen one. The{" "}
            <em>ordering</em> — capture the report first, verify identity afterwards — is the real
            design decision; the gateway behind it is simulated.
          </StatusRow>
          <StatusRow label="Sessions" status="Real">
            Session cookies and server-side session records are implemented the way a production
            system would build them (HTTP-only, short expiry, explicit logout) — even though the
            credential that creates them is a mocked OTP.
          </StatusRow>
          <StatusRow label="Passwords" status="Not built">
            There is no password anywhere in this product. Nothing to leak, nothing to hash
            badly.
          </StatusRow>
          <StatusRow label="Evidence &quot;scanning&quot;" status="Simulated">
            Any file you attach is marked with a simulated clean-scan status. No antivirus or
            malware scanning actually runs on uploaded files.
          </StatusRow>
          <StatusRow label="Encryption at rest" status="Not built">
            The prototype database has no field-level encryption, no key management, and no
            access-control layer. A production system handling real complaint narratives, contact
            details and evidence would need all of these — they are designed for, in the data
            model, but not implemented here.
          </StatusRow>
          <StatusRow label="Notifications (SMS / email)" status="Simulated">
            Status-update messages are rendered on screen exactly as they would be sent. Nothing
            is actually delivered to any phone or inbox.
          </StatusRow>
          <StatusRow label="Bank freeze / CFCFRMS coordination" status="Not built">
            Nothing you submit here is sent to any bank, to CFCFRMS, or to any nodal freeze
            system. The report is stored in this prototype&apos;s own database only.
          </StatusRow>
          <StatusRow label="Connection to any real government system" status="Not built">
            This prototype is not connected to cybercrime.gov.in, NCRP, CFCFRMS, or any other
            government system, in any direction. It is prohibited by the hackathon&apos;s own
            rules, and we would not have built it that way regardless.
          </StatusRow>
        </CardContent>
      </Card>

      <div className="flex flex-col gap-4">
        <h2 className="text-xl font-semibold tracking-tight text-foreground">
          Why Aadhaar, PAN, and DigiLocker are not here
        </h2>
        <p className="text-sm text-muted-foreground">
          This is a deliberate product decision, not an oversight, and not something we ran out
          of time for. We evaluated each one against a single question:{" "}
          <em>does it help freeze the money, route the case, or contact the victim faster?</em> If
          the answer was no, it does not belong in the product.
        </p>

        <Card>
          <CardHeader>
            <CardTitle className="text-base">Aadhaar — not collected, not integrated, not mocked</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-2 text-sm text-muted-foreground">
            <p>
              Using real Aadhaar numbers is explicitly on this hackathon&apos;s prohibited list.
              Beyond that rule, a hackathon team has no lawful basis to authenticate against
              Aadhaar at all: UIDAI&apos;s own onboarding form requires a declared statutory
              basis (a government subsidy, benefit or service, or another Act of Parliament) that
              a prototype simply doesn&apos;t have, and the private-entity authentication route
              that once existed under Section 57 of the Aadhaar Act was removed by law in 2019,
              specifically to stop private parties from doing this. Even a fake &quot;Verify with
              Aadhaar&quot; button would be worse than omitting it — it would normalise the exact
              request scammers make to victims after they report a fraud.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-base">PAN — never asked, never stored</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-2 text-sm text-muted-foreground">
            <p>
              PAN doesn&apos;t help freeze the money (that depends on the beneficiary account or
              UPI ID, not the victim&apos;s tax identity), doesn&apos;t help route the complaint
              (routing is by the complainant&apos;s State and District), and doesn&apos;t help
              reach the victim (that&apos;s the mobile number). It is a permanent, sensitive
              financial identifier with no functional benefit here, so there is no column for it
              anywhere in this product&apos;s database.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="text-base">DigiLocker — designed, deliberately mocked, kept out of this build</CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-2 text-sm text-muted-foreground">
            <p>
              DigiLocker is genuinely the best-shaped identity idea of the three — it&apos;s
              consent-based, it fetches a document rather than collecting a number, and the
              citizen holds the credential rather than us. But real onboarding requires an
              incorporated entity with regulatory authorisation to authenticate the relevant
              document class, which this prototype does not have. More decisively:{" "}
              <strong className="text-foreground">
                there is no DigiLocker test sandbox
              </strong>{" "}
              — the official onboarding SOP says plainly that no requests for temporary test
              access will be entertained. There was no honest way to demonstrate a working
              DigiLocker call in this build, so it isn&apos;t here — not even as a labelled mock
              button. If it is ever built, it must be optional, consent-first, permanently
              labelled &quot;Simulated — not connected to DigiLocker&quot;, and skippable in one
              tap.
            </p>
          </CardContent>
        </Card>

        <p className="text-sm text-muted-foreground">
          What we built instead: a small profile — name (optional), mobile number, and State +
          District — created only after you file a report, never as a gate before it. That is the
          entire identity system in this product.
        </p>
      </div>

      <Separator />

      <div className="flex flex-col gap-4">
        <h2 className="text-xl font-semibold tracking-tight text-foreground">
          Known limitations
        </h2>
        <p className="text-sm text-muted-foreground">Known bugs: none, at time of writing.</p>
        <ul className="flex flex-col gap-3 text-sm text-muted-foreground">
          <li>
            <strong className="text-foreground">DigiLocker cannot be live-tested.</strong> No
            sandbox exists and the official process refuses temporary test access. Any DigiLocker
            element in this product is a labelled design mock or it does not exist.
          </li>
          <li>
            <strong className="text-foreground">
              Aadhaar is excluded by both law and the hackathon&apos;s own rules
            </strong>{" "}
            — not a design preference.
          </li>
          <li>
            <strong className="text-foreground">
              India&apos;s DPDP data-protection rules are not yet legally binding.
            </strong>{" "}
            The substantive obligations (notice, consent, security safeguards, breach
            notification, erasure) come into force on 13 May 2027; a consent-manager rule follows
            on 13 Nov 2026. We build to that standard now, as forward-compliance — but we do not
            and cannot claim to be &quot;DPDP compliant&quot; today, because most of the law
            isn&apos;t in force yet. See <Link href="/privacy" className="underline underline-offset-2 hover:text-foreground">/privacy</Link>.
          </li>
          <li>
            <strong className="text-foreground">No automated test suite exists.</strong> A
            deliberate three-day tradeoff, stated openly rather than hidden.
          </li>
          <li>
            <strong className="text-foreground">
              The prototype has no production security and cannot claim any.
            </strong>{" "}
            Mocked OTP, simulated virus scanning, no encryption at rest, no real access control.
          </li>
          <li>
            <strong className="text-foreground">
              Three problems stay named and unsolved:
            </strong>{" "}
            getting complaints converted into FIRs, the quality of police follow-up after a
            complaint is filed, and 1930&apos;s call capacity and language routing. A better web
            form doesn&apos;t fix any of these, and we are not pretending it does.
          </li>
        </ul>
      </div>

      <p className="text-sm text-muted-foreground">
        Read more about what this product does and does not attempt to solve on{" "}
        <Link href="/help/just-happened" className="underline underline-offset-2 hover:text-foreground">
          /help/just-happened
        </Link>
        , or see our{" "}
        <Link href="/accessibility" className="underline underline-offset-2 hover:text-foreground">
          accessibility statement
        </Link>{" "}
        and{" "}
        <Link href="/privacy" className="underline underline-offset-2 hover:text-foreground">
          privacy notice
        </Link>
        .
      </p>
    </div>
  );
}
